els-ASAP auto commit file/tag rusers-0.17-61.el6.src.rpm

diff --git a/rstatd.init b/rstatd.init
--- a/rstatd.init
+++ b/rstatd.init
@@ -7,8 +7,8 @@
 
 ### BEGIN INIT INFO
 # Provides: rpc.rstatd
-# Required-Start: $syslog $network
-# Required-Stop:  $syslog $network
+# Required-Start: $syslog $network $rpcbind
+# Required-Stop:  $syslog $network $rpcbind
 # Default-Start:
 # Default-Stop: 0 1 2 3 4 5 6
 # Short-Description: start and stop rpc.rstatd
@@ -27,6 +27,7 @@
 RETVAL=0
 LOCK="/var/lock/subsys/rpc.rstatd"
 PIDFILE="/var/run/rpc.rstatd.pid"
+RSTAT_RPC_NUM=100001
 
 start() {
     if [ $UID -ne 0 ] ; then
@@ -38,12 +39,34 @@ start() {
     then
 	    exit 6 #considered not configured
     fi
+	status rpcbind > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && /etc/rc.d/init.d/rpcbind start
 	echo -n $"Starting rstat services: "
 	daemon rpc.rstatd
 	RETVAL=$?
-
-	echo
+	# Check that rpc service has been registred successfully
+	if [ $RETVAL -eq 0 ] 
+	then
+		timeout=3
+		SECONDS=0
+		while [ $SECONDS -lt $timeout ]; do
+			rpcinfo -u localhost $RSTAT_RPC_NUM > /dev/null 2>&1
+			RETVAL=$?
+			if [ $RETVAL -eq 0 ]; then
+				break;
+			fi
+			sleep 1
+		done
+		if [ $RETVAL -ne 0 ]; then
+			logger -t rpc.rstatd "rstatd cannot bind to rpcbind."
+			failure
+		fi
+	else
+		failure
+	fi
 	[ $RETVAL -eq 0 ] && touch $LOCK && touch $PIDFILE
+	echo
 	return $RETVAL
 }	
 
diff --git a/rusersd.init b/rusersd.init
--- a/rusersd.init
+++ b/rusersd.init
@@ -7,8 +7,8 @@
 
 ### BEGIN INIT INFO
 # Provides: rpc.rusersd
-# Required-Start: $syslog $network
-# Required-Stop:  $syslog $network
+# Required-Start: $syslog $network $rpcbind
+# Required-Stop:  $syslog $network $rpcbind
 # Default-Start:
 # Default-Stop: 0 1 2 3 4 5 6
 # Short-Description: start and stop rpc.rusersd
@@ -27,6 +27,7 @@
 RETVAL=0
 LOCK="/var/lock/subsys/rpc.rusersd"
 PIDFILE="/var/run/rpc.rusersd.pid"
+RUSERS_RPC_NUM=100002
 
 start() {
     if [ $UID -ne 0 ] ; then
@@ -36,7 +37,7 @@ start() {
     # Check that networking is up.
     if [ ${NETWORKING} = "no" ]
     then
-	  exit 0
+	  exit 6 #considered not configured
     fi
 	status rpcbind > /dev/null
 	RETVAL=$?
@@ -44,8 +45,28 @@ start() {
 	echo -n $"Starting rusers services: "
 	daemon rpc.rusersd
 	RETVAL=$?
-	echo
+	 # Check that rpc service has been registred successfully
+        if [ $RETVAL -eq 0 ]
+        then
+                timeout=3
+                SECONDS=0
+                while [ $SECONDS -lt $timeout ]; do
+                        rpcinfo -u localhost $RUSERS_RPC_NUM > /dev/null 2>&1
+                        RETVAL=$?
+                        if [ $RETVAL -eq 0 ]; then
+                                break;
+                        fi
+                        sleep 1
+                done
+                if [ $RETVAL -ne 0 ]; then
+                        logger -t rpc.rstatd "rusersd cannot bind to rpcbind."
+                        failure
+                fi
+        else
+                failure
+        fi
 	[ $RETVAL -eq 0 ] && touch $LOCK && touch $PIDFILE
+	echo
 	return $RETVAL
 }
 
